language: php
php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - chmod -R 777 app/storage

script:
  - phpunit

notifications:
  emails:
    - myu1107@gmail.com

#language: python
#python:
#   - "3.5"
#script: py.test
